// HandDetector.idl : HandDetector.exe에 대한 형식 라이브러리 소스

// 이 파일은 MIDL 컴파일러에 의해 처리되어
// 형식 라이브러리(HandDetector.tlb)를 생성합니다.

[ uuid(69F7CA08-4243-45A0-BE50-7DACDBCE4F58), version(1.0) ]
library HandDetector
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  CHandDetectorDoc의 기본 디스패치 인터페이스
	
	[ uuid(CEF7A77E-C7BC-4BE8-9AC3-1B0A10C13AE4) ]
	dispinterface IHandDetector
	{
		properties:
			
		methods:
	};

	//  CHandDetectorDoc의 클래스 정보
	
	[ uuid(74C65160-5A12-4963-8795-65782A73CC27) ]
	coclass CHandDetectorDoc
	{
		[default] dispinterface IHandDetector;
	};
};
